import { ArrowUpRight, ArrowRight, Mail, Phone } from 'lucide-react';
import { company, sectors } from './site-data';
export function SiteHeader() {
  return <><a className="skip-link" href="#main-content">Skip to content</a><header className="site-header wrap"><a href="/" className="wordmark" aria-label="Kins West Trading home"><span className="wordmark-main">KINS WEST<span className="brand-point">.</span></span><span className="wordmark-sub">TRADING CO.</span></a><nav aria-label="Main navigation"><a href="/#sectors">Our sectors</a><a href="/#company">Company</a><a className="header-contact" href="/#contact">Get in touch <ArrowUpRight size={17} /></a></nav></header></>;
}
export function Contact() {
  return <section className="contact-section" id="contact"><div className="wrap contact-grid"><div><p className="eyebrow">LET’S TALK</p><h2>Your next project<br />starts here.</h2><p>Tell us about your supply, storage or delivery needs.<br />We’ll discuss the scope of your project.</p></div><div className="contact-links"><a href={`mailto:${company.email}`}><span className="contact-label"><Mail size={17} /> EMAIL</span><span>{company.email}<ArrowUpRight size={24} /></span></a><a href={`tel:${company.phone}`}><span className="contact-label"><Phone size={17} /> PHONE</span><span>{company.displayPhone}<ArrowUpRight size={24} /></span></a></div></div></section>;
}
export function SiteFooter() {
  return <footer className="site-footer wrap"><div className="footer-grid"><div><a href="/" className="wordmark"><span className="wordmark-main">KINS WEST<span className="brand-point">.</span></span><span className="wordmark-sub">TRADING CO.</span></a><p>B2B trade.<br />EU warehousing. Logistics.</p></div><div><p className="footer-label">OUR SECTORS</p>{sectors.map(s => <a key={s.slug} href={`/categories/${s.slug}`}>{s.title}</a>)}</div><div><p className="footer-label">REGISTERED OFFICE</p><address>{company.address}</address></div><div><p className="footer-label">COMPANY DETAILS</p><p>{company.name}<br />Company No. {company.number}<br />Registered in England and Wales</p><a className="registry-link" href={company.registry} target="_blank" rel="noreferrer">Companies House <ArrowUpRight size={15} /></a></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} {company.name}</span><a href="#main-content">Back to top <ArrowRight size={15} className="arrow-top" /></a></div></footer>;
}
